### PR TITLE
fix(fe): changed naive ui datatable to pagination table

### LINKED ISSUE #757: Admin dashboard workbook pagination table 수정
### Describe the problem and solution

admin dashboard pagination table 이 현재는 naive-ui로 구현했는데 naive-ui의 구현과는 다르게 코드당에서는 마지막 페이지에 접근할 수 없기 때문에 우리가 만든 컴포넌트로 대체한다. 그리고 페이지 스타일도 수정된 figma에 맞게 바꾼다. 
workbook.vue를 수정한다

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

### PR DESCRIPTION
**Pull request by EliseCho13**
### Description

admin dashboard페이지의 workbook 페이지네이션에 사용된 naive ui dataTable을 페이지네이션 테이블로 변경했습니다.
Close #757 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/793"></a>

### CODE REVIEW

File: frontend/src/admin/pages/workbook.vue [hunk 1]
```diff
@@ -1,84 +1,80 @@
...
   {
-    title: '#',
+    label: '#',
     key: 'id',
-    minWidth: 80
+    width: '8%'
   },
   {
-    title: 'Group',
+    label: 'Group',
```
Comment (eunnbi) [inline frontend/src/admin/pages/workbook.vue:34]: `Group` 라벨 지워주세요! 피그마 변경되었어요~

File: frontend/src/admin/pages/workbook.vue [hunk 2]
```diff
@@ -1,84 +1,80 @@
...
   {
-    title: 'Title',
-    key: 'title'
+    label: 'Title',
+    key: 'title',
+    width: '30%'
   },
   {
-    title: 'Period',
+    label: 'Period',
```
Comment (eunnbi) [inline frontend/src/admin/pages/workbook.vue:44]: `Period` 라벨 지워주세요~

**Review by eunnbi — APPROVED** [review]
