### PR TITLE
fix(fe): transform type

### LINKED ISSUE #888: [Bug]: Problem이 안 만들어져요
### Describe the bug

문제를 만들 때 input element에서 반환되는 값이 string이어서 type 오류가 발생합니다.

image

Zod validation에서 transform을 적용하면 될 것 같습니다...
https://zod.dev/?id=transform

```ts
timeLimit: z.string().default('2000')transform((v) => parseInt(v))
```

### Reproduction

1. Admin dashboard에서 문제 생성

### Logs

_No response_

### System Info

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

### PR DESCRIPTION
**Pull request by Kohminchae**
### Description

transform으로 timelimit의 type 을 바꿈
close #888 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

<a href="https://gitpod.io/#https://github.com/skkuding/codedang/pull/889"></a>

### CODE REVIEW

File: frontend/src/admin/components/CreateProblemModal.vue [hunk 1]
```diff
@@ -49,7 +49,10 @@ const schema = z.object({
     .array(z.enum(['C', 'Cpp', 'Python3', 'Java', 'Golang']))
     .min(1, 'At least one language is required.')
     .default([]),
-  timeLimit: z.number().default(2000),
+  timeLimit: z
+    .string()
+    .default('2000')
+    .transform((v) => parseInt(v)),
   memoryLimit: z.number().default(512),
```
Comment (dotoleeoak) [inline frontend/src/admin/components/CreateProblemModal.vue:56]: 여기도 `timeLimit`처럼 바꿔야될 거 같아요...

**Review by dotoleeoak — CHANGES_REQUESTED** [review]

**Review by dotoleeoak — APPROVED** [review]
