### PR TITLE
fix(fe): edit username password conditions

### LINKED ISSUE #1250: signup username password 조건 통일
### Describe the problem and solution

* 기획 및 프론트
username: 3-10자 영문 대소문자 및 숫자 허용
password: 8-20자 모든 문자 허용
* 백엔드
username: 3-10자 영문 소문자 및 숫자 허용
password: 8자 이상 영문 소문자, 대문자, 숫자 중 2가지 이상 혼합

백엔드 기준으로 통일합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

### PR DESCRIPTION
**Pull request by B0XERCAT**
### Description
* userId와 password의 조건을 백엔드 기준에 맞춰 수정
userId: 3-10자 영문 소문자 및 숫자 허용
password: 8자 이상 영문 소문자, 대문자, 숫자 중 2가지 이상 사용
* userId와 password 조건 text 수정
image
image

Close #1250 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by youznn** [comment]
수고하셨습니다!

File: frontend-client/app/(main)/_components/SignUpRegister.tsx [hunk 1]
```diff
@@ -169,8 +175,8 @@ export default function SignUpRegister() {
             <div className="mt-1 text-xs text-gray-500">
               <p>&#x2022; User ID used for log in</p>
               <p>
-                &#x2022; Your ID must be 3-10 characters of alphabet
-                &nbsp;&nbsp;letters, numbers
+                &#x2022; Your ID must be 3-10 characters of small
+                &nbsp;&nbsp;&nbsp;&nbsp;alphabet letters, numbers
```
Comment (dayongkr) [inline frontend-client/app/(main)/_components/SignUpRegister.tsx:179]: css style로 대체하기

**Review by dayongkr — APPROVED** [review]
