### PR TITLE
fix(fe): edit login and signup modal

### LINKED ISSUE #1380: 로그인 및 회원가입 모달 수정
### Describe the problem and solution

1. 모달 각 페이지의 메인 버튼을 엔터로도 제출
2. 인증코드 input에 arrows 제거
3. 인증코드 타이머 설정 및 재전송 버튼
4. 로그인 모달 ID -> User ID
5. dialog 바깥 클릭해도 창 닫지 못하게

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

### PR DESCRIPTION
**Pull request by B0XERCAT**
### Description
1. ID를 User ID로 수정
2. email 버튼 클릭 없이 엔터만 눌러도 전송
3. Verification Code input에 arrows 제거
4. 5분 타이머 설정
5. dialog 바깥 클릭으로 인한 모달 닫힘 방지
image
image

Close #1380 
### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

File: frontend-client/app/(main)/_components/SignUpEmailVerify.tsx [hunk 1]
```diff
@@ -38,6 +42,29 @@ export default function SignUpEmailVerify() {
...
+
+  useEffect(() => {
+    let interval: string | number | NodeJS.Timeout | undefined
+    if (sentEmail && timer > 0) {
+      interval = setInterval(() => {
+        setTimer((prevTimer) => prevTimer - 1)
+      }, 1000)
+    }
+    return () => clearInterval(interval)
+  }, [sentEmail, timer])
```
Comment (aintbe) [inline frontend-client/app/(main)/_components/SignUpEmailVerify.tsx:54]: 이것도 좋은데, react-use의 `useInterval`을 쓰면 좀 더 좋을 것 같습니다 :)
https://streamich.github.io/react-use/?path=/story/animation-useinterval--docs

Comment (B0XERCAT) [reply frontend-client/app/(main)/_components/SignUpEmailVerify.tsx]: useInterval 사용해서 수정했습니다!

**Review by aintbe — APPROVED** [review]
수고하셨습니다!
